apiVersion: v1
kind: Service
metadata:
  name: builder
  namespace: deployx
  labels:
    app: builder
    app.kubernetes.io/name: builder
    app.kubernetes.io/part-of: deployx-platform
spec:
  type: ClusterIP
  selector:
    app: builder
  ports:
    - name: http
      port: 3002
      targetPort: 3002
      protocol: TCP
