apiVersion: v1
kind: Service
metadata:
  name: billing
  namespace: deployx
  labels:
    app: billing
    app.kubernetes.io/name: billing
    app.kubernetes.io/part-of: deployx-platform
spec:
  type: ClusterIP
  selector:
    app: billing
  ports:
    - name: http
      port: 3003
      targetPort: 3003
      protocol: TCP
