apiVersion: v1
kind: ConfigMap
metadata:
  name: sentry-config
  namespace: deployx
data:
  SENTRY_ENVIRONMENT: production
  SENTRY_TRACES_SAMPLE_RATE: "0.2"
---
apiVersion: v1
kind: Secret
metadata:
  name: sentry-secrets
  namespace: deployx
type: Opaque
stringData:
  SENTRY_DSN_API: ""
  SENTRY_DSN_WEB: ""
