apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: deployx
  labels:
    app: web
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: deployx-platform
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
