import {
  Framework,
  GitProvider,
  DeploymentStatus,
  DeploymentType,
  BuildStage,
  Plan,
  MembershipRole,
  SslStatus,
  InvoiceStatus,
  SubscriptionStatus,
} from "@deployx/shared";

// ============ USERS ============
export const mockUser = {
  id: "usr_1",
  email: "alex@deployx.dev",
  name: "Alex Chen",
  avatarUrl: "",
  orgId: "org_1",
  role: MembershipRole.OWNER,
  mfaEnabled: true,
  createdAt: new Date("2024-01-15"),
  updatedAt: new Date("2024-12-01"),
};

export const mockOrg = {
  id: "org_1",
  name: "DeployX",
  slug: "deployx",
  plan: Plan.PRO,
  ownerId: "usr_1",
  createdAt: new Date("2024-01-15"),
  updatedAt: new Date("2024-12-01"),
};

// ============ PROJECTS ============
export const mockProjects = [
  {
    id: "proj_1",
    name: "deployx-web",
    slug: "deployx-web",
    framework: Framework.NEXTJS,
    gitProvider: GitProvider.GITHUB,
    repositoryUrl: "https://github.com/deployx/web",
    branch: "main",
    rootDirectory: ".",
    buildCommand: "next build",
    outputDirectory: ".next",
    installCommand: "npm install",
    orgId: "org_1",
    isPrivate: true,
    domain: "deployx.dev",
    latestDeployment: { status: DeploymentStatus.READY, commitSha: "a1b2c3d", commitMessage: "feat: add dashboard charts", time: "2 hours ago" },
    collaborators: ["AC", "JD", "MK"],
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "proj_2",
    name: "deployx-api",
    slug: "deployx-api",
    framework: Framework.NODE,
    gitProvider: GitProvider.GITHUB,
    repositoryUrl: "https://github.com/deployx/api",
    branch: "main",
    rootDirectory: ".",
    buildCommand: "npm run build",
    outputDirectory: "dist",
    installCommand: "npm install",
    orgId: "org_1",
    isPrivate: true,
    domain: "api.deployx.dev",
    latestDeployment: { status: DeploymentStatus.READY, commitSha: "e4f5g6h", commitMessage: "fix: rate limiter config", time: "5 hours ago" },
    collaborators: ["AC", "RS"],
    createdAt: new Date("2024-04-01"),
    updatedAt: new Date("2024-11-28"),
  },
  {
    id: "proj_3",
    name: "docs-portal",
    slug: "docs-portal",
    framework: Framework.ASTRO,
    gitProvider: GitProvider.GITLAB,
    repositoryUrl: "https://gitlab.com/deployx/docs",
    branch: "main",
    rootDirectory: ".",
    buildCommand: "astro build",
    outputDirectory: "dist",
    installCommand: "npm install",
    orgId: "org_1",
    isPrivate: false,
    domain: "docs.deployx.dev",
    latestDeployment: { status: DeploymentStatus.READY, commitSha: "i7j8k9l", commitMessage: "docs: update API reference", time: "1 day ago" },
    collaborators: ["MK", "JD"],
    createdAt: new Date("2024-05-15"),
    updatedAt: new Date("2024-11-25"),
  },
  {
    id: "proj_4",
    name: "marketing-site",
    slug: "marketing-site",
    framework: Framework.VITE,
    gitProvider: GitProvider.GITHUB,
    repositoryUrl: "https://github.com/deployx/marketing",
    branch: "main",
    rootDirectory: ".",
    buildCommand: "vite build",
    outputDirectory: "dist",
    installCommand: "npm install",
    orgId: "org_1",
    isPrivate: false,
    domain: "www.deployx.dev",
    latestDeployment: { status: DeploymentStatus.ERROR, commitSha: "m0n1o2p", commitMessage: "feat: new pricing section", time: "3 days ago" },
    collaborators: ["RS", "AC"],
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "proj_5",
    name: "admin-dashboard",
    slug: "admin-dashboard",
    framework: Framework.REMIX,
    gitProvider: GitProvider.GITLAB,
    repositoryUrl: "https://gitlab.com/deployx/admin",
    branch: "main",
    rootDirectory: ".",
    buildCommand: "remix build",
    outputDirectory: "build",
    installCommand: "npm install",
    orgId: "org_1",
    isPrivate: true,
    domain: "admin.deployx.dev",
    latestDeployment: { status: DeploymentStatus.READY, commitSha: "q3r4s5t", commitMessage: "feat: user management page", time: "6 hours ago" },
    collaborators: ["AC"],
    createdAt: new Date("2024-07-10"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "proj_6",
    name: "blog",
    slug: "blog",
    framework: Framework.NUXT,
    gitProvider: GitProvider.GITHUB,
    repositoryUrl: "https://github.com/deployx/blog",
    branch: "main",
    rootDirectory: ".",
    buildCommand: "nuxt build",
    outputDirectory: ".output",
    installCommand: "npm install",
    orgId: "org_1",
    isPrivate: false,
    domain: "blog.deployx.dev",
    latestDeployment: { status: DeploymentStatus.BUILDING, commitSha: "u6v7w8x", commitMessage: "feat: dark mode support", time: "10 minutes ago" },
    collaborators: ["JD", "MK", "RS"],
    createdAt: new Date("2024-08-01"),
    updatedAt: new Date("2024-12-01"),
  },
];

// ============ DEPLOYMENTS ============
export const mockDeployments = [
  {
    id: "dep_1",
    projectId: "proj_1",
    branch: "main",
    commitSha: "a1b2c3d",
    commitMessage: "feat: add dashboard charts",
    status: DeploymentStatus.READY,
    type: DeploymentType.PRODUCTION,
    buildStage: BuildStage.READY,
    author: { name: "Alex Chen", avatar: "", fallback: "AC" },
    duration: 95000,
    createdAt: new Date("2024-12-01T10:30:00"),
    url: "https://deployx.dev",
  },
  {
    id: "dep_2",
    projectId: "proj_1",
    branch: "feat/auth",
    commitSha: "b2c3d4e",
    commitMessage: "feat: OAuth2 integration",
    status: DeploymentStatus.READY,
    type: DeploymentType.PREVIEW,
    buildStage: BuildStage.READY,
    author: { name: "Jane Doe", avatar: "", fallback: "JD" },
    duration: 72000,
    createdAt: new Date("2024-12-01T08:15:00"),
    url: "https://feat-auth-deployx-web.deployx.dev",
  },
  {
    id: "dep_3",
    projectId: "proj_1",
    branch: "main",
    commitSha: "c3d4e5f",
    commitMessage: "fix: header responsive layout",
    status: DeploymentStatus.ERROR,
    type: DeploymentType.PRODUCTION,
    buildStage: BuildStage.BUILDING,
    author: { name: "Alex Chen", avatar: "", fallback: "AC" },
    duration: 45000,
    createdAt: new Date("2024-11-30T16:45:00"),
    url: "",
  },
  {
    id: "dep_4",
    projectId: "proj_2",
    branch: "main",
    commitSha: "e4f5g6h",
    commitMessage: "fix: rate limiter config",
    status: DeploymentStatus.READY,
    type: DeploymentType.PRODUCTION,
    buildStage: BuildStage.READY,
    author: { name: "Raj Singh", avatar: "", fallback: "RS" },
    duration: 68000,
    createdAt: new Date("2024-12-01T07:00:00"),
    url: "https://api.deployx.dev",
  },
  {
    id: "dep_5",
    projectId: "proj_3",
    branch: "main",
    commitSha: "i7j8k9l",
    commitMessage: "docs: update API reference",
    status: DeploymentStatus.READY,
    type: DeploymentType.PRODUCTION,
    buildStage: BuildStage.READY,
    author: { name: "Maria Kim", avatar: "", fallback: "MK" },
    duration: 34000,
    createdAt: new Date("2024-11-30T12:00:00"),
    url: "https://docs.deployx.dev",
  },
  {
    id: "dep_6",
    projectId: "proj_1",
    branch: "fix/typo",
    commitSha: "d4e5f6g",
    commitMessage: "fix: landing page typos",
    status: DeploymentStatus.READY,
    type: DeploymentType.PREVIEW,
    buildStage: BuildStage.READY,
    author: { name: "Jane Doe", avatar: "", fallback: "JD" },
    duration: 55000,
    createdAt: new Date("2024-11-29T14:20:00"),
    url: "https://fix-typo-deployx-web.deployx.dev",
  },
  {
    id: "dep_7",
    projectId: "proj_4",
    branch: "main",
    commitSha: "m0n1o2p",
    commitMessage: "feat: new pricing section",
    status: DeploymentStatus.ERROR,
    type: DeploymentType.PRODUCTION,
    buildStage: BuildStage.BUILDING,
    author: { name: "Raj Singh", avatar: "", fallback: "RS" },
    duration: 120000,
    createdAt: new Date("2024-11-28T09:30:00"),
    url: "",
  },
  {
    id: "dep_8",
    projectId: "proj_5",
    branch: "main",
    commitSha: "q3r4s5t",
    commitMessage: "feat: user management page",
    status: DeploymentStatus.READY,
    type: DeploymentType.PRODUCTION,
    buildStage: BuildStage.READY,
    author: { name: "Alex Chen", avatar: "", fallback: "AC" },
    duration: 88000,
    createdAt: new Date("2024-12-01T06:00:00"),
    url: "https://admin.deployx.dev",
  },
  {
    id: "dep_9",
    projectId: "proj_6",
    branch: "main",
    commitSha: "u6v7w8x",
    commitMessage: "feat: dark mode support",
    status: DeploymentStatus.BUILDING,
    type: DeploymentType.PRODUCTION,
    buildStage: BuildStage.INSTALLING,
    author: { name: "Jane Doe", avatar: "", fallback: "JD" },
    duration: 0,
    createdAt: new Date("2024-12-01T11:00:00"),
    url: "",
  },
  {
    id: "dep_10",
    projectId: "proj_1",
    branch: "main",
    commitSha: "a1b2c3d",
    commitMessage: "feat: add dashboard charts",
    status: DeploymentStatus.QUEUED,
    type: DeploymentType.ROLLBACK,
    buildStage: BuildStage.CLONING,
    author: { name: "Alex Chen", avatar: "", fallback: "AC" },
    duration: 0,
    createdAt: new Date("2024-12-01T11:05:00"),
    url: "",
  },
  {
    id: "dep_11",
    projectId: "proj_2",
    branch: "feat/webhooks",
    commitSha: "h5g6f7e",
    commitMessage: "feat: webhook delivery system",
    status: DeploymentStatus.READY,
    type: DeploymentType.PREVIEW,
    buildStage: BuildStage.READY,
    author: { name: "Maria Kim", avatar: "", fallback: "MK" },
    duration: 61000,
    createdAt: new Date("2024-11-29T10:00:00"),
    url: "https://feat-webhooks-deployx-api.deployx.dev",
  },
  {
    id: "dep_12",
    projectId: "proj_1",
    branch: "main",
    commitSha: "a1b2c3d",
    commitMessage: "chore: update dependencies",
    status: DeploymentStatus.CANCELLED,
    type: DeploymentType.PRODUCTION,
    buildStage: BuildStage.INSTALLING,
    author: { name: "Alex Chen", avatar: "", fallback: "AC" },
    duration: 12000,
    createdAt: new Date("2024-11-27T15:30:00"),
    url: "",
  },
];

// ============ DOMAINS ============
export const mockDomains = [
  { id: "dom_1", name: "deployx.dev", projectId: "proj_1", sslStatus: SslStatus.ISSUED, verifiedAt: new Date("2024-03-15"), createdAt: new Date("2024-03-10") },
  { id: "dom_2", name: "www.deployx.dev", projectId: "proj_1", sslStatus: SslStatus.ISSUED, verifiedAt: new Date("2024-03-15"), createdAt: new Date("2024-03-10") },
  { id: "dom_3", name: "api.deployx.dev", projectId: "proj_1", sslStatus: SslStatus.PENDING, createdAt: new Date("2024-11-28") },
  { id: "dom_4", name: "staging.deployx.dev", projectId: "proj_1", sslStatus: SslStatus.ERROR, createdAt: new Date("2024-11-20") },
];

// ============ TEAM MEMBERS ============
export const mockMembers = [
  { id: "mem_1", userId: "usr_1", name: "Alex Chen", email: "alex@deployx.dev", avatar: "", role: MembershipRole.OWNER, joinedAt: new Date("2024-01-15"), lastActive: new Date("2024-12-01"), mfaEnabled: true },
  { id: "mem_2", userId: "usr_2", name: "Jane Doe", email: "jane@deployx.dev", avatar: "", role: MembershipRole.ADMIN, joinedAt: new Date("2024-02-10"), lastActive: new Date("2024-12-01"), mfaEnabled: true },
  { id: "mem_3", userId: "usr_3", name: "Maria Kim", email: "maria@deployx.dev", avatar: "", role: MembershipRole.MEMBER, joinedAt: new Date("2024-03-05"), lastActive: new Date("2024-11-30"), mfaEnabled: false },
  { id: "mem_4", userId: "usr_4", name: "Raj Singh", email: "raj@deployx.dev", avatar: "", role: MembershipRole.MEMBER, joinedAt: new Date("2024-04-20"), lastActive: new Date("2024-11-29"), mfaEnabled: true },
  { id: "mem_5", userId: "usr_5", name: "Sam Wilson", email: "sam@deployx.dev", avatar: "", role: MembershipRole.VIEWER, joinedAt: new Date("2024-06-01"), lastActive: new Date("2024-11-15"), mfaEnabled: false },
];

export const mockPendingInvites = [
  { id: "inv_1", email: "newdev@company.com", role: MembershipRole.MEMBER, invitedBy: "Alex Chen", invitedAt: new Date("2024-11-28") },
  { id: "inv_2", email: "pm@company.com", role: MembershipRole.VIEWER, invitedBy: "Jane Doe", invitedAt: new Date("2024-11-25") },
];

// ============ BILLING ============
export const mockSubscription = {
  id: "sub_1",
  orgId: "org_1",
  plan: Plan.PRO,
  status: SubscriptionStatus.ACTIVE,
  currentPeriodStart: new Date("2024-11-01"),
  currentPeriodEnd: new Date("2024-12-01"),
  cancelAtPeriodEnd: false,
  createdAt: new Date("2024-02-01"),
  updatedAt: new Date("2024-11-01"),
};

export const mockUsage = {
  bandwidth: { used: 456, limit: 1000, unit: "GB" },
  buildMinutes: { used: 15200, limit: 24000, unit: "min" },
  invocations: { used: 680, limit: 1000, unit: "GB-hrs" },
  storage: { used: 12, limit: 50, unit: "GB" },
};

export const mockInvoices = [
  { id: "inv_2024_11", orgId: "org_1", amount: 20.00, currency: "USD", status: InvoiceStatus.PAID, dueDate: new Date("2024-11-01"), paidAt: new Date("2024-11-01"), createdAt: new Date("2024-11-01") },
  { id: "inv_2024_10", orgId: "org_1", amount: 20.00, currency: "USD", status: InvoiceStatus.PAID, dueDate: new Date("2024-10-01"), paidAt: new Date("2024-10-01"), createdAt: new Date("2024-10-01") },
  { id: "inv_2024_09", orgId: "org_1", amount: 20.00, currency: "USD", status: InvoiceStatus.PAID, dueDate: new Date("2024-09-01"), paidAt: new Date("2024-09-02"), createdAt: new Date("2024-09-01") },
  { id: "inv_2024_08", orgId: "org_1", amount: 20.00, currency: "USD", status: InvoiceStatus.OPEN, dueDate: new Date("2024-12-01"), createdAt: new Date("2024-12-01") },
];

export const mockPaymentMethods = [
  { id: "pm_1", brand: "visa", last4: "4242", expiryMonth: 12, expiryYear: 2025, isDefault: true },
  { id: "pm_2", brand: "mastercard", last4: "8888", expiryMonth: 6, expiryYear: 2026, isDefault: false },
];

// ============ AUDIT LOG ============
export const mockAuditLogs = [
  { id: "al_1", timestamp: new Date("2024-12-01T10:30:00"), user: { name: "Alex Chen", avatar: "", fallback: "AC" }, action: "deployment.created", resource: "deployx-web", resourceType: "project", ipAddress: "192.168.1.100", details: "Deployed commit a1b2c3d to production" },
  { id: "al_2", timestamp: new Date("2024-12-01T09:15:00"), user: { name: "Jane Doe", avatar: "", fallback: "JD" }, action: "member.invited", resource: "newdev@company.com", resourceType: "member", ipAddress: "10.0.0.42", details: "Invited as MEMBER role" },
  { id: "al_3", timestamp: new Date("2024-11-30T16:45:00"), user: { name: "Alex Chen", avatar: "", fallback: "AC" }, action: "project.settings_updated", resource: "deployx-web", resourceType: "project", ipAddress: "192.168.1.100", details: "Updated build command" },
  { id: "al_4", timestamp: new Date("2024-11-30T14:00:00"), user: { name: "Maria Kim", avatar: "", fallback: "MK" }, action: "domain.added", resource: "api.deployx.dev", resourceType: "domain", ipAddress: "172.16.0.5", details: "Added domain to deployx-web" },
  { id: "al_5", timestamp: new Date("2024-11-30T11:30:00"), user: { name: "Raj Singh", avatar: "", fallback: "RS" }, action: "env.updated", resource: "deployx-api", resourceType: "project", ipAddress: "10.0.0.88", details: "Updated 3 environment variables" },
  { id: "al_6", timestamp: new Date("2024-11-29T09:00:00"), user: { name: "Alex Chen", avatar: "", fallback: "AC" }, action: "org.settings_updated", resource: "DeployX", resourceType: "organization", ipAddress: "192.168.1.100", details: "Updated organization name" },
  { id: "al_7", timestamp: new Date("2024-11-28T15:20:00"), user: { name: "Jane Doe", avatar: "", fallback: "JD" }, action: "webhook.created", resource: "deployx-web", resourceType: "project", ipAddress: "10.0.0.42", details: "Created webhook for deployment events" },
  { id: "al_8", timestamp: new Date("2024-11-28T10:00:00"), user: { name: "Alex Chen", avatar: "", fallback: "AC" }, action: "token.created", resource: "CI/CD Token", resourceType: "token", ipAddress: "192.168.1.100", details: "Created token with deployment scope" },
];

// ============ ANALYTICS ============
export const mockAnalytics = {
  visitors: 12450,
  pageViews: 48230,
  bounceRate: 34.2,
  avgDuration: 185,
  trafficOverTime: [
    { date: "Nov 25", visitors: 1200, pageViews: 4500 },
    { date: "Nov 26", visitors: 1400, pageViews: 5200 },
    { date: "Nov 27", visitors: 1100, pageViews: 4100 },
    { date: "Nov 28", visitors: 1600, pageViews: 6100 },
    { date: "Nov 29", visitors: 1800, pageViews: 6800 },
    { date: "Nov 30", visitors: 2100, pageViews: 7900 },
    { date: "Dec 01", visitors: 1900, pageViews: 7200 },
  ],
  topPages: [
    { page: "/", views: 12450 },
    { page: "/docs", views: 8900 },
    { page: "/pricing", views: 5600 },
    { page: "/blog", views: 4200 },
    { page: "/docs/api", views: 3100 },
  ],
  topReferrers: [
    { referrer: "Google", visits: 5400 },
    { referrer: "GitHub", visits: 3200 },
    { referrer: "Twitter", visits: 1800 },
    { referrer: "Hacker News", visits: 1200 },
    { referrer: "Direct", visits: 980 },
  ],
};

// ============ ENV VARS ============
export const mockEnvVars = {
  production: [
    { id: "ev_1", key: "DATABASE_URL", value: "postgresql://user:pass@host:5432/prod_db", target: "production" },
    { id: "ev_2", key: "NEXT_PUBLIC_API_URL", value: "https://api.deployx.dev", target: "production" },
    { id: "ev_3", key: "JWT_SECRET", value: "sk_live_abc123xyz789", target: "production" },
    { id: "ev_4", key: "REDIS_URL", value: "redis://default@host:6379", target: "production" },
  ],
  preview: [
    { id: "ev_5", key: "DATABASE_URL", value: "postgresql://user:pass@host:5432/preview_db", target: "preview" },
    { id: "ev_6", key: "NEXT_PUBLIC_API_URL", value: "https://api-staging.deployx.dev", target: "preview" },
  ],
  development: [
    { id: "ev_7", key: "DATABASE_URL", value: "postgresql://localhost:5432/dev_db", target: "development" },
    { id: "ev_8", key: "NEXT_PUBLIC_API_URL", value: "http://localhost:3001", target: "development" },
  ],
};

// ============ BUILD LOGS ============
export const mockBuildLogs = [
  { id: "bl_1", timestamp: "10:30:01", level: "info" as const, message: "Cloning repository from https://github.com/deployx/web", group: "Clone" },
  { id: "bl_2", timestamp: "10:30:03", level: "info" as const, message: "Cloning completed in 2.1s", group: "Clone" },
  { id: "bl_3", timestamp: "10:30:04", level: "info" as const, message: "Detected framework: Next.js", group: "Install" },
  { id: "bl_4", timestamp: "10:30:04", level: "info" as const, message: "Running: npm install", group: "Install" },
  { id: "bl_5", timestamp: "10:30:15", level: "info" as const, message: "npm install completed in 11.2s", group: "Install" },
  { id: "bl_6", timestamp: "10:30:16", level: "info" as const, message: "Running: next build", group: "Build" },
  { id: "bl_7", timestamp: "10:30:18", level: "info" as const, message: "  Creating an optimized production build...", group: "Build" },
  { id: "bl_8", timestamp: "10:30:22", level: "info" as const, message: "  Compiled successfully", group: "Build" },
  { id: "bl_9", timestamp: "10:30:23", level: "warn" as const, message: "  Warning: Image with src may be slow when not using next/image", group: "Build" },
  { id: "bl_10", timestamp: "10:30:25", level: "info" as const, message: "  Generating static pages (12/12)", group: "Build" },
  { id: "bl_11", timestamp: "10:30:26", level: "info" as const, message: "  Finalizing page optimization...", group: "Build" },
  { id: "bl_12", timestamp: "10:30:27", level: "success" as const, message: "Build completed in 11.4s", group: "Build" },
  { id: "bl_13", timestamp: "10:30:28", level: "info" as const, message: "Deploying to edge network...", group: "Deploy" },
  { id: "bl_14", timestamp: "10:30:32", level: "info" as const, message: "Uploading assets (34 files, 2.4MB total)", group: "Deploy" },
  { id: "bl_15", timestamp: "10:30:35", level: "info" as const, message: "Configuring CDN distribution...", group: "Deploy" },
  { id: "bl_16", timestamp: "10:30:38", level: "success" as const, message: "Deployment complete! Available at https://deployx.dev", group: "Deploy" },
];

export const mockRuntimeLogs = [
  { id: "rl_1", timestamp: "10:31:01", level: "info" as const, message: "Server started on port 3000" },
  { id: "rl_2", timestamp: "10:31:02", level: "info" as const, message: "Connected to PostgreSQL database" },
  { id: "rl_3", timestamp: "10:31:05", level: "info" as const, message: "GET /api/health 200 12ms" },
  { id: "rl_4", timestamp: "10:31:10", level: "info" as const, message: "GET / 200 45ms" },
  { id: "rl_5", timestamp: "10:31:12", level: "info" as const, message: "GET /docs 200 38ms" },
  { id: "rl_6", timestamp: "10:31:15", level: "warn" as const, message: "Rate limit approaching for IP 192.168.1.100 (85/100)" },
  { id: "rl_7", timestamp: "10:31:20", level: "info" as const, message: "POST /api/deployments 201 156ms" },
  { id: "rl_8", timestamp: "10:31:25", level: "error" as const, message: "Failed to send webhook notification: Connection timeout after 5000ms" },
  { id: "rl_9", timestamp: "10:31:30", level: "info" as const, message: "GET /api/projects 200 22ms" },
  { id: "rl_10", timestamp: "10:31:35", level: "info" as const, message: "WebSocket connection established" },
  { id: "rl_11", timestamp: "10:31:40", level: "info" as const, message: "GET /api/deployments?projectId=proj_1 200 31ms" },
  { id: "rl_12", timestamp: "10:31:45", level: "warn" as const, message: "Memory usage at 78% - consider scaling up" },
];

// ============ USAGE CHART DATA ============
export const mockUsageChartData = {
  "7d": [
    { date: "Nov 25", bandwidth: 52, requests: 12400 },
    { date: "Nov 26", bandwidth: 68, requests: 15200 },
    { date: "Nov 27", bandwidth: 45, requests: 11800 },
    { date: "Nov 28", bandwidth: 72, requests: 16800 },
    { date: "Nov 29", bandwidth: 81, requests: 18400 },
    { date: "Nov 30", bandwidth: 95, requests: 21200 },
    { date: "Dec 01", bandwidth: 88, requests: 19600 },
  ],
  "30d": [
    { date: "Nov 02", bandwidth: 42, requests: 9800 },
    { date: "Nov 05", bandwidth: 55, requests: 12400 },
    { date: "Nov 08", bandwidth: 48, requests: 11200 },
    { date: "Nov 11", bandwidth: 61, requests: 14600 },
    { date: "Nov 14", bandwidth: 58, requests: 13800 },
    { date: "Nov 17", bandwidth: 70, requests: 16200 },
    { date: "Nov 20", bandwidth: 75, requests: 17800 },
    { date: "Nov 23", bandwidth: 68, requests: 15600 },
    { date: "Nov 26", bandwidth: 82, requests: 18900 },
    { date: "Nov 29", bandwidth: 90, requests: 20100 },
    { date: "Dec 01", bandwidth: 88, requests: 19600 },
  ],
};

// ============ REPOSITORIES (for import) ============
export const mockRepositories = [
  { id: "repo_1", name: "deployx/web", fullName: "deployx/web", private: true, updatedAt: new Date("2024-12-01T10:00:00"), provider: GitProvider.GITHUB },
  { id: "repo_2", name: "deployx/api", fullName: "deployx/api", private: true, updatedAt: new Date("2024-12-01T07:00:00"), provider: GitProvider.GITHUB },
  { id: "repo_3", name: "deployx/docs", fullName: "deployx/docs", private: false, updatedAt: new Date("2024-11-30T12:00:00"), provider: GitProvider.GITHUB },
  { id: "repo_4", name: "deployx/mobile-app", fullName: "deployx/mobile-app", private: true, updatedAt: new Date("2024-11-29T15:00:00"), provider: GitProvider.GITHUB },
  { id: "repo_5", name: "personal/portfolio", fullName: "alexchen/portfolio", private: false, updatedAt: new Date("2024-11-25T09:00:00"), provider: GitProvider.GITHUB },
  { id: "repo_6", name: "deployx/infrastructure", fullName: "deployx/infrastructure", private: true, updatedAt: new Date("2024-11-28T11:00:00"), provider: GitProvider.GITLAB },
  { id: "repo_7", name: "deployx/analytics", fullName: "deployx/analytics", private: true, updatedAt: new Date("2024-11-27T14:00:00"), provider: GitProvider.GITLAB },
];

// ============ WEBHOOKS ============
export const mockWebhooks = [
  { id: "wh_1", url: "https://api.myapp.com/webhooks/deploy", events: ["deployment.created", "deployment.ready"], secret: "whsec_abc123", createdAt: new Date("2024-10-01") },
  { id: "wh_2", url: "https://hooks.slack.com/services/T00/B00/xxx", events: ["deployment.error"], secret: "whsec_def456", createdAt: new Date("2024-11-15") },
];

// ============ TOKENS ============
export const mockTokens = [
  { id: "tok_1", name: "CI/CD Pipeline", scopes: ["deployment:create", "deployment:read"], createdAt: new Date("2024-08-01"), lastUsed: new Date("2024-12-01") },
  { id: "tok_2", name: "GitHub Actions", scopes: ["project:read", "deployment:create"], createdAt: new Date("2024-09-15"), lastUsed: new Date("2024-11-30") },
];
